# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PbOc1P9oEI6182uihv4GCt_6L_8NypAI
"""

#1
length=int(input("Enter length of rectangle : "))
width=int(input("Enter width of rectangle : "))

area=length*width
print("Area of rectangle : ",area)

#2
height=float(input("Enter height in Meters: "))
weight=float(input("Enter weight in KGs : "))

BMI=weight/(height**2)

print("BMI : ",BMI)

#3
students_score={'Name':'Akshansh','score':90}
print(students_score)

#4
age=int(input("Enter your age : "))

if age<18:
  print("You are Minor")
elif age>60 :
  print("You are Senior")
else :
  print("You are Adult")

#5
for i in range(1,51):
  if i%2==0:
    print(i,end=",")

#6

#7

def list_average():
  mylist=[22,34,56,34,56]
  lsum=0
  for i in mylist:
    lsum += i
    average=lsum/len(mylist)

  print(average)

list_average()

#8

def vowel_count(str):
	count = 0
	vowel = set("aeiouAEIOU")
	for alphabet in str:
		if alphabet in vowel:
			count = count + 1
	print("No. of vowels :", count)
str = "Akshansh"

vowel_count(str)

#9
from datetime import datetime

current_datetime = datetime.now()
print("current date and time :", current_datetime)

#10

a=10
b='Akshansh'
try:
  a+b
except:
  print("Enter only numeric value")

#11

try:
  a=int(input("Enter number : "))
except:
  print("Enter numeric values only")

#12
a=12
b=0
try:
  a/b
except:
  print("Denominator cannot be 0 ")

#13
# nfl=open('text_file.txt','x')
# nfl=open('text_file.txt','w')
# 'text_file.txt'.write("Hello Python!")

#14
print(nfl)

#15
nfl.append()=("asdfghjk")
nfl.read()